org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=1.21.3
  yarn_mappings=1.21.3+build.2
  loader_version=0.16.9
  fabric_version=0.108.0+1.21.3

# Mod Properties
  group=com.sollace
  displayname=Stringer Things
  authors=Sollace, PhoenixSC
  description=Things, made out of Strings

# Publishing
  minecraft_version_range=>=1.21
  modrinth_loader_type=fabric
  modrinth_project_id=3bbkaIXw

# Dependencies
  modmenu_version=12.0.0-beta.1

